drawing-line:
	python3 drawing-line.py

drawing-line-with-image:
	python3 drawing-line-with-image.py

read-image:
	python3 read-image.py

read-camera:
	python3 read-camera.py

read-video:
	python3 read-video.py
