01: 01-handling-double-type-input.c
	gcc -o bin/01-handling-double-type-input 01-handling-double-type-input.c
	bin/01-handling-double-type-input

02: 02-string-input.c
	gcc -o bin/02-string-input 02-string-input.c
	bin/02-string-input
